version: "3.8"

services:
  zero:
    image: dgraph/dgraph:latest
    container_name: csv_graph_zero
    volumes:
      - ~/csv_graph:/dgraph
    ports:
      - 5080:5080
      - 6080:6080
    command: >
      dgraph zero --my=zero:5080 
      --logtostderr -v=1

  alpha:
    image: dgraph/dgraph:v25.0.0-preview4
    container_name: csv_graph_alpha
    volumes:
      - ~/csv_graph:/dgraph
      - ../data:/data
    ports:
      - 8080:8080
      - 9080:9080
    command: >
      dgraph alpha --my=alpha:7080 --zero=zero:5080
        --security whitelist=0.0.0.0/0
        --logtostderr -v=1
        --mcp
