name: FOAF Graph

#on:
#  push:
#    paths:
#      - '.actions/**'
#      - 'docker/foaf_graph/build/**'

on:
  push:
    branches:
      - matthewmcneely/foaf-image-update

permissions:
  contents: read
  packages: write

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: docker/foaf_graph/build
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/hypermodeinc/dgraph-foaf-graph:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
          labels: |
            org.opencontainers.image.source=https://github.com/${{ github.repository }}
            org.opencontainers.image.description=FOAF Graph Docker Image
            org.opencontainers.image.licenses=MIT
          provenance: false