#
name: Push FOAF Graph

env:
  IMAGE_NAME: dgraph-foaf-graph

on:
  push:
    branches:
      - matthewmcneely/foaf-image-update

jobs:
  # This pushes the image to GitHub Packages.
  push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      #
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: docker/foaf_graph/build
          push: true
          tags: hypermodeinc/dgraph-foaf-graph:latest